# from win32api import GetSystemMetrics


# window variables
WINDOW_NAME = "Smartnode"
WINDOW_X_POS = 300
WINDOW_Y_POS = 100
WINDOW_W_RATIO = 5/8
WINDOW_L_RATIO = 7/8

# BUTTON_HEIGHT = 11
# BUTTON_WIDTH = 200
BUTTON_HEIGHT = 0
BUTTON_WIDTH = 26
BUTTON_DEPTH = 4
BUTTON_SPACE = 2

BUTTON_COLOR = "#2F3FFF"
BUTTON_PRESS_COLOR = "#0F0FFF"
BUTTON_PADY = 2

TITLE_COLOR = "#FF007F"
TITLE_DEPTH = 8
TITLE_PADY = 10

FONT_COLOR = "#FFFFFF"

BACKGROUND_COLOR = "#5F6FFF"
# WINDOW_W, WINDOW_L = WINDOW_SIZE = round(GetSystemMetrics(0) * WINDOW_W_RATIO),\
#                                                           round(GetSystemMetrics(1) * WINDOW_L_RATIO)
# print(WINDOW_W, WINDOW_L, WINDOW_SIZE)


# WINDOW_W, WINDOW_L = WINDOW_SIZE = 1024, 900
WINDOW_W, WINDOW_L = WINDOW_SIZE = 800, 480
# WINDOW_W, WINDOW_L = WINDOW_SIZE = GetSystemMetrics(0), GetSystemMetrics(1)  # for windows
